FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    mysql-client \
    openssh-server \
    python3 python3-pip sudo

RUN mkdir -p /var/run/sshd

# GENERAR HOST KEYS
RUN ssh-keygen -A

# Usuario cepy
RUN useradd -m -s /bin/bash cepy && \
    echo "cepy:castelar" | chpasswd && \
    usermod -aG sudo cepy

# Permitir password
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]